import {InMemoryDbService} from 'angular-in-memory-web-api';
export class InMemoryDataService implements InMemoryDbService {

    createDb() {
        let products = [
            {
                id: 1,
                name: 'HP 15-AC650TU Portable 4th Gen Intel Core i5 Processor-4GB RAM-1TB',
                image: 'app/chunks/images/hp1.jpg',
                price: '52000',
                requiredQuantity: 1,
                quantity: '5',
                company: 'HP',
                processor: 'Intel Core i5 Processor',
                ram: '4GB',
                hardDisk: '1TB',
                operatingSystem: 'Win 8',
                screenSize: "15'",
                color: "Black"
            },
            {
                id: 2,
                name: 'HP 15-AC169TU 15.6-inch Laptop (Intel Core i7 Processor/4GB/1TB/Win 7)',
                image: 'app/chunks/images/hp2.jpg',
                price: '55000',
                requiredQuantity: 1,
                quantity: '6',
                company: 'HP',
                processor: 'Intel Core i7 Processor',
                ram: '4GB',
                hardDisk: '1TB',
                operatingSystem: 'Win 8',
                screenSize: "15.6'",
                color: "Black"
            },
            {
                id: 3,
                name: 'HP 14-AC250TU 14.6-inch Laptop (Intel Core i7 Processor/4GB/1TB/Win 7)',
                image: 'app/chunks/images/hp3.jpg',
                price: '42000',
                requiredQuantity: 1,
                quantity: '4',
                company: 'HP',
                processor: 'Intel Core i7 Processor',
                ram: '8GB',
                hardDisk: '1TB',
                operatingSystem: 'Win 7',
                screenSize: "14.6'",
                color: "Black"
            },
            {
                id: 4,
                name: 'HP 13AU25TU 13.6-inch Laptop (Intel Core i3 Processor/4GB/500GB)',
                image: 'app/chunks/images/hp4.jpg',
                price: '32000',
                requiredQuantity: 1,
                quantity: '6',
                company: 'HP',
                processor: 'Intel Core i3 Processor',
                ram: '4GB',
                hardDisk: '500GB',
                operatingSystem: 'Win 10',
                screenSize: "13.6'",
                color: "Black"
            },
            {
                id: 5,
                name: 'Dell vostro 15R 3558TU 15.6-inch Laptop (Intel Core i3/4GB/500GB /15.6)',
                image: 'app/chunks/images/dell1.jpg',
                price: '32000',
                requiredQuantity: 1,
                quantity: '7',
                company: 'Dell',
                processor: 'Intel Core i3 Processor',
                ram: '4GB',
                hardDisk: '500GB',
                operatingSystem: 'Win 10',
                screenSize: "15.6'",
                color: "Red"
            },
            {
                id: 6,
                name: 'Dell Inspiron 15 5559 14-inch Laptop (Intel Core i7/16GB/2TB HDD/Win 7)',
                image: 'app/chunks/images/dell2.jpg',
                price: '65000',
                requiredQuantity: 1,
                quantity: '5',
                company: 'Dell',
                processor: 'Intel Core i3 Processor',
                ram: '16GB',
                hardDisk: '2TB',
                operatingSystem: 'Win 7',
                screenSize: "14'",
                color: "Silver"
            },
            {
                id: 7,
                name: 'Dell vostro 15 3558 15.6-inch Laptop (Intel Core i5/ 8GB/1TB HDD/ Win 8)',
                image: 'app/chunks/images/dell3.jpg',
                price: '62000',
                requiredQuantity: 1,
                quantity: '7',
                company: 'Dell',
                processor: 'Intel Core i5 Processor',
                ram: '8GB',
                hardDisk: '1TB',
                operatingSystem: 'Win 8',
                screenSize: "15.6'",
                color: "Black"
            },
            {
                id: 8,
                name: 'Dell Inspiron 15R 4580 15.6-inch Laptop (Intel Core i5/4GB/1TB /Win 10)',
                image: 'app/chunks/images/dell4.jpg',
                price: '52000',
                requiredQuantity: 1,
                quantity: '7',
                company: 'Dell',
                processor: 'Intel Core i5 Processor',
                ram: '4GB',
                hardDisk: '1TB',
                operatingSystem: 'Win 10',
                screenSize: "15.6'",
                color: "Black"
            },
            {
                id: 9,
                name: 'Lenovo G50-70 15.6-inch Laptop (Intel Core i3/4GB/500GB/Win 8.1), Silver',
                image: 'app/chunks/images/lenovo1.jpg',
                price: '32000',
                requiredQuantity: 1,
                quantity: '5',
                company: 'Lenovo',
                processor: 'Intel Core i3 Processor',
                ram: '4GB',
                hardDisk: '500GB',
                operatingSystem: 'Win 10',
                screenSize: "15.6'",
                color: "Silver"
            },
            {
                id: 10,
                name: 'Lenovo G51-55 14-inch Laptop (Intel Core i5/4GB/1TB/ Win 8/2GB Graphics)',
                image: 'app/chunks/images/lenovo2.jpg',
                price: '52000',
                requiredQuantity: 1,
                quantity: '5',
                company: 'Lenovo',
                processor: 'Intel Core i5 Processor',
                ram: '4GB',
                hardDisk: '1TB',
                operatingSystem: 'Win 8',
                screenSize: "14'",
                color: "Silver"
            },
            {
                id: 11,
                name: 'Lenovo G71 15.6-inch Laptop (Intel Core i7/16GB/3TB/Win 10/2GB Graphics',
                image: 'app/chunks/images/lenovo3.jpg',
                price: '72000',
                requiredQuantity: 1,
                quantity: '5',
                company: 'Lenovo',
                processor: 'Intel Core i7 Processor',
                ram: '16GB',
                hardDisk: '3TB',
                operatingSystem: 'Win 10',
                screenSize: "15.6'",
                color: "Black"
            },
            {
                id: 12,
                name: 'Lenovo G57-78 13-inch Laptop (Intel Core i3/4GB/1TB/Win 7/ 2GB Graphics)',
                image: 'app/chunks/images/lenovo4.jpg',
                price: '45000',
                requiredQuantity: 1,
                quantity: '5',
                company: 'Lenovo',
                processor: 'Intel Core i3 Processor',
                ram: '4GB',
                hardDisk: '1TB',
                operatingSystem: 'Win 7',
                screenSize: "15.6'",
                color: "Black"
            },
            {
                id: 13,
                name: 'Apple Macbook Pro MD101HN/A 13-inch Laptop (Intel Core i5/4GB/500GB/Mac',
                image: 'app/chunks/images/apple1.jpg',
                price: '72000',
                requiredQuantity: 1,
                quantity: '5',
                company: 'Apple',
                processor: 'Intel Core i5 Processor',
                ram: '4GB',
                hardDisk: '500GB',
                operatingSystem: 'Mac OS',
                screenSize: "13'",
                color: "Silver"
            },
            {
                id: 14,
                name: 'Apple Macbook Pro MD102 14-inch Laptop (Intel Core i5/8GB/1TB/Mac OS)',
                image: 'app/chunks/images/apple2.jpg',
                price: '72000',
                requiredQuantity: 1,
                quantity: '7',
                company: 'Apple',
                processor: 'Intel Core i5 Processor',
                ram: '8GB',
                hardDisk: '1TB',
                operatingSystem: 'Mac OS',
                screenSize: "14'",
                color: "Pink"
            },
            {
                id: 15,
                name: 'Apple Macbook Pro MD103 13-inch Laptop (Intel Core i3/4GB/1TB/Mac OS)',
                image: 'app/chunks/images/apple3.jpg',
                price: '72000',
                requiredQuantity: 1,
                quantity: '9',
                company: 'Apple',
                processor: 'Intel Core i3 Processor',
                ram: '4GB',
                hardDisk: '1TB',
                operatingSystem: 'Mac OS',
                screenSize: "15.6'",
                color: "Silver"
            },
            {
                id: 16,
                name: 'Apple Macbook Pro MD105 15-inch Laptop (Intel Core i7/8GB/2TB/Mac OS)',
                image: 'app/chunks/images/apple4.jpg',
                price: '92000',
                requiredQuantity: 1,
                quantity: '2',
                company: 'Apple',
                processor: 'Intel Core i7 Processor',
                ram: '8GB',
                hardDisk: '2TB',
                operatingSystem: 'Mac OS',
                screenSize: "15'",
                color: "Silver"
            },
            {
                id: 17,
                name: 'HP 13-AC200 13.6-inch Laptop (Intel Core i3 Processor/4GB/1TB/Win 10)',
                image: 'app/chunks/images/hp5.jpg',
                price: '45000',
                requiredQuantity: 1,
                quantity: '6',
                company: 'HP',
                processor: 'Intel Core i3 Processor',
                ram: '4GB',
                hardDisk: '1TB',
                operatingSystem: 'Win 10',
                screenSize: "13.6'",
                color: "Silver"
            },

        ];
        let inListProducts = [
            {
                id: 1,
                name: 'HP 15-AC650TU Portable 4th Gen Intel Core i5 Processor-4GB RAM-1TB',
                image: 'app/chunks/images/hp1.jpg',
                price: '52000',
                requiredQuantity: 1,
                quantity: '5',
                company: 'HP',
                processor: 'Intel Core i5 Processor',
                ram: '4GB',
                hardDisk: '1TB',
                operatingSystem: 'DOS',
                screenSize: "15'",
                color: "Black"
            }];
        let inCartProducts = [
            {
                id: 1,
                name: 'HP 15-AC650TU Portable 4th Gen Intel Core i5 Processor-4GB RAM-1TB',
                image: 'app/chunks/images/hp1.jpg',
                price: '62000',
                requiredQuantity: 1,
                quantity: '5',
                company: 'HP',
                processor: 'Intel Core i5 Processor',
                ram: '4GB',
                hardDisk: '1TB',
                operatingSystem: 'DOS',
                screenSize: "15'",
                color: "Black"
            }];
        return {products, inListProducts, inCartProducts};
    }
}
